illinois-ceesd/logpyle

.github/workflows/ci.yaml

separate flake8 from example

---

bin/runalyzer-gather

clarify assert

---

.github/workflows/ci.yaml
logpyle/runalyzer.py

label plots automatically

---

.github/workflows/ci.yaml

Fixes the CI issue and run tests with versions 3.6-3.9.

CI: test Python versions 3.6-3.9

---

.github/workflows/ci.yaml

fix macos 3.9

---

examples/log.py

Helps expose bugs such as #33 and better illustrates usage.

example: print all quantities

---

logpyle/__init__.py

Otherwise, measuring time through 'with' context does not work (ie, always returns 0).

Intervaltimer: don't forget to submit time

---

bin/runalyzer-gather
logpyle/__init__.py

- Modes 'wu' / 'wo' were ignored. Fixed.
- ~Default `runalyzer-gather` multi-run mode still ignores warnings.~ Fixed.

fix warning collection

---

.github/workflows/ci.yaml

Fixes the recent CI failures we have seen (https://github.com/illinois-ceesd/logpyle/actions)

Fix CI oversubscription error with Open MPI

---

logpyle/__init__.py

print watch units

---

logpyle/runalyzer.py

Interferes with automating runalyzer

remove INFO message

---

examples/log-mpi.py
logpyle/__init__.py

custom format for watches

---

logpyle/version.py

```
$ git tag -a vXXXX.X
$ twine upload dist/logpyle-XXXX.X*
```

release 2021.0

---

.github/workflows/ci.yaml
examples/log.py
logpyle/__init__.py

allow setting custom watch interval

---

logpyle/__init__.py

Add back start_sub_timer to IntervalTimer docstring

---

examples/log.py
logpyle/__init__.py

Solves off-by-one error and partially addresses #70.

LogUpdateDuration: convert to PostLogQuantity

---

logpyle/version.py

```
$ git tag -a vXXXX.X
$ twine upload dist/logpyle-XXXX.X*
```

release 2023.0

---

logpyle/version.py

```
$ git tag -a vXXXX.X
$ twine upload dist/logpyle-XXXX.X*
```

release 2023.1

---

examples/log.py
logpyle/__init__.py

add GCStats

---

logpyle/__init__.py

fix InitTime

---

.github/workflows/ci.yaml

better CI checks

---

bin/runalyzer-gather

runalyzer-gather: remove single mode

---

.github/workflows/ci.yaml
bin/runalyzer-gather
examples/log-mpi.py
examples/log.py
logpyle/__init__.py
logpyle/runalyzer.py

Modeled after the warnings capture.

capture logging messages

---

bin/runalyzer
doc/log.rst

make mangling mode default

---

logpyle/version.py

```
$ git tag -a vXXXX.X
$ twine upload dist/logpyle-XXXX.X*
```

Release v2023.2

---

logpyle/__init__.py

end logging capture on close

---

logpyle/version.py

```
$ REL=2023.2.1
$ git checkout main
```

Release v2023.2.1

---

logpyle/version.py

```
$ REL=2023.2.2
$ git checkout main
```

Release 2023.2.2

---

logpyle/version.py

```
$ REL=2023.2.3
$ git checkout main
```

Release 2023.2.3

---

doc/log.rst
logpyle/__init__.py

CPUTime -> WallTime

---

test/test_logManager.py
test/test_quantities.py
test/testlib.py

Quantities:
LogQuantity, PostLogQuantity, MultiLogQuantity, and MultiPostLogQuantity.
A testlib file was also created to separate fixtures from implementation.

Tests added for custom some quantities.

---

.github/workflows/ci.yaml
run-mypy.sh
test/conftest.py
test/test_logManager.py
test/test_quantities.py

Added flake8 compatibility to the test suite

Add static analyzers targeting test suite in CI

---

logpyle/__init__.py
test/test_logManager.py

Implemented pop function on event counter and re-enabled tests

---

logpyle/__init__.py
test/test_logManager.py

join_by_first_of_tuple fix

---

logpyle/version.py

```
$ REL=2023.3
$ git checkout main && git pull
```

Release 2023.3

---

logpyle/version.py

```
$ REL=2023.4
$ git checkout main && git pull
```

Release v2023.4

---

logpyle/version.py

```console
$ REL=2023.4.1 && git checkout main && git pull && git tag -a v$REL -m "Release v$REL" && git push --tags
```

release 2023.4.1

---

.github/workflows/ci.yaml

This hopefully fixes the intermittent CI errors.

CI: add another oversubscribe option
